---
title: "Final Project"
author: "Rikke Uldbæk"
date: "3/20/2023"
output: html_document
---

```{r setup, include=FALSE}

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)


#set wd
setwd("~/Library/Mobile Documents/com~apple~CloudDocs/Cognitive Science/6th_semester/spatial_analytics/final_project_SA")

#loading packages
pacman::p_load(sf, raster, tidyverse, rmdformats, opencage, leaflet, mapboxapi, Rccp, fasterize, st)
install.packages("Rccp")
library(Rccp)

```



### Load data
```{r}


data <- read_excel("./data/cult_activities_aarhus.xls")
ls.str(data)
data$Latitude <- as.numeric(data$Latitude)
data$Longitude <- as.numeric(data$Longitude)


```



### Preprocess data 

# Mapbox for distances

```{r}
#setwd("~/Library/Mobile Documents/com~apple~CloudDocs/Cognitive Science/6th_semester/spatial_analytics/cds-spatial/Week05")

# either paste it in directly, or in a txt file that you store locally and "ignore"
my_token <- read_file("mytoken.txt")

my_token

library(mapboxapi)
#readRenviron("~/.Renviron")
mb_access_token(my_token, install = TRUE, overwrite = TRUE)
```




